# Directory containing raw FASTQ files (relative to repo root)
input_dir: "data/fastq"

# Output directory (relative to repo root)
output_dir: "results"

# DADA2 formatted database
taxa_db: "data/db/dada2_formatted_rpoc_amplicon.fasta"

# Kraken2 database
kraken_db: "data/db/kraken_amplicon"

# Threads
threads: 20

# Default taxonomy assignment method
method: "kraken2"

# KO inference
ko_db_fasta: "data/db/kraken2_amplicons.fasta"
ko_npz: "data/db/all_genomes_kos.npz"
ko_genomes: "data/db/all_genomes_kos_genomes.txt"
ko_list: "data/db/all_genomes_kos_kos.txt"
identity_threshold: 0.4

# Optional metadata file (set to "none" if not provided)
metadata: "config/metadata.tsv"

# Paired-end suffixes
read1_suffix: "_R1.fastq.gz"
read2_suffix: "_R2.fastq.gz"
